param(
    [int]$StartYear = 2025,
    [int]$EndYear = 2035
)
$ErrorActionPreference = 'Stop'

function U([int[]]$codes) { -join ($codes | ForEach-Object { [char]$_ }) }
function Escape-Ics([string]$value) { $value.Replace('\', '\\').Replace(';', '\;').Replace(',', '\,').Replace("`r", '').Replace("`n", '\n') }
function Write-Calendar([string]$sourceId, [string]$calendarName, [string]$category, [object[]]$rules, [string]$output, [string]$scope) {
    $calendar = New-Object System.Globalization.ChineseLunisolarCalendar
    $events = New-Object 'System.Collections.Generic.List[object]'
    foreach ($lunarYear in ($StartYear - 1)..$EndYear) {
        foreach ($rule in $rules) {
            try {
                $date = $calendar.ToDateTime($lunarYear, $rule.Month, $rule.Day, 0, 0, 0, 0)
            } catch [System.ArgumentOutOfRangeException] {
                continue
            }
            if ($date.Year -lt $StartYear -or $date.Year -gt $EndYear) { continue }
            $events.Add([pscustomobject]@{ Date=$date; Name=$rule.Name; Id=$rule.Id })
        }
    }
    $lines = @('BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CalRepo//Chinese Religious Observances//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',"X-WR-CALNAME:$calendarName",'X-WR-TIMEZONE:Asia/Shanghai',"X-CALREPO-SOURCE-ID:$sourceId",'X-CALREPO-VERSION:2026.07.25')
    foreach ($event in ($events | Sort-Object Date, Name)) {
        $start = $event.Date.ToString('yyyyMMdd')
        $end = $event.Date.AddDays(1).ToString('yyyyMMdd')
        $uid = "calrepo.$($sourceId.ToLower()).$($event.Id).$start@calrepo.com"
        $description = "Chinese lunar date generated by the .NET ChineseLunisolarCalendar. Scope: $scope"
        $lines += @('BEGIN:VEVENT',"UID:$uid",'DTSTAMP:20260725T120000Z',"DTSTART;VALUE=DATE:$start","DTEND;VALUE=DATE:$end","SUMMARY:$(Escape-Ics $event.Name)","DESCRIPTION:$(Escape-Ics $description)","CATEGORIES:$(Escape-Ics $category)",'END:VEVENT')
    }
    $lines += 'END:VCALENDAR'
    [IO.Directory]::CreateDirectory((Split-Path -Parent $output)) | Out-Null
    [IO.File]::WriteAllBytes($output, [Text.UTF8Encoding]::new($false).GetBytes(($lines -join "`r`n") + "`r`n"))
    Write-Output "generated $($events.Count) events: $output"
}

$hanBuddhist = @(
    @{ Id='buddha-renunciation'; Month=2; Day=8; Name=U @(37322,36838,29279,23612,20315,20986,23478,26085) }, @{ Id='buddha-parinirvana'; Month=2; Day=15; Name=U @(37322,36838,29279,23612,20315,28037,27075,26085) }, @{ Id='guanyin-birthday'; Month=2; Day=19; Name=U @(35266,19990,38899,33769,33832,22307,35806) }, @{ Id='samantabhadra-birthday'; Month=2; Day=21; Name=U @(26222,36132,33769,33832,22307,35806) }, @{ Id='zhunti-birthday'; Month=3; Day=16; Name=U @(20934,25552,33769,33832,22307,35806) }, @{ Id='manjushri-birthday'; Month=4; Day=4; Name=U @(25991,27530,33769,33832,22307,35806) }, @{ Id='buddha-birthday'; Month=4; Day=8; Name=U @(37322,36838,29279,23612,20315,22307,35806) }, @{ Id='vesak'; Month=4; Day=15; Name=U @(20315,21513,31077,26085) }, @{ Id='medicine-king-birthday'; Month=4; Day=28; Name=U @(33647,29579,33769,33832,22307,35806) }, @{ Id='skanda-birthday'; Month=6; Day=3; Name=U @(38886,39534,33769,33832,22307,35806) }, @{ Id='guanyin-enlightenment'; Month=6; Day=19; Name=U @(35266,19990,38899,33769,33832,25104,36947,26085) }, @{ Id='mahasthamaprapta-birthday'; Month=7; Day=13; Name=U @(22823,21183,33267,33769,33832,22307,35806) }, @{ Id='ullambana'; Month=7; Day=15; Name=U @(20315,27426,21916,26085,65288,30402,20848,30406,33410,65289) }, @{ Id='nagarjuna-birthday'; Month=7; Day=24; Name=U @(40857,26641,33769,33832,22307,35806) }, @{ Id='ksitigarbha-birthday'; Month=7; Day=30; Name=U @(22320,34255,33769,33832,22307,35806) }, @{ Id='moonlight-bodhisattva-birthday'; Month=8; Day=15; Name=U @(26376,20809,33769,33832,22307,35806) }, @{ Id='dipankara-birthday'; Month=8; Day=22; Name=U @(29123,28783,20315,22307,35806) }, @{ Id='guanyin-ordination'; Month=9; Day=19; Name=U @(35266,19990,38899,33769,33832,20986,23478,26085) }, @{ Id='medicine-buddha-birthday'; Month=9; Day=30; Name=U @(33647,24072,29705,29827,20809,20315,22307,35806) }, @{ Id='amitabha-birthday'; Month=11; Day=17; Name=U @(38463,24357,38464,20315,22307,35806) }, @{ Id='buddha-enlightenment'; Month=12; Day=8; Name=U @(37322,36838,29279,23612,20315,25104,36947,26085) }, @{ Id='huayan-bodhisattva-birthday'; Month=12; Day=29; Name=U @(21326,20005,33769,33832,22307,35806) }
)
$taoist = @(
    @{ Id='heavenly-wax'; Month=1; Day=1; Name=U @(22825,33098,20043,36784) }, @{ Id='jade-emperor-birthday'; Month=1; Day=9; Name=U @(29577,30343,19978,24093,22307,35806) }, @{ Id='shangyuan'; Month=1; Day=15; Name=U @(19978,20803,22825,23448,22307,35806) }, @{ Id='laojun-birthday'; Month=2; Day=15; Name=U @(22826,19978,32769,21531,22307,35806) }, @{ Id='xuantiandi-birthday'; Month=3; Day=3; Name=U @(29572,22825,19978,24093,22307,35806) }, @{ Id='zhao-gongming-birthday'; Month=3; Day=15; Name=U @(36130,31070,36213,20844,26126,22307,35806) }, @{ Id='luzu-birthday'; Month=4; Day=14; Name=U @(21525,31062,32431,38451,31062,24072,22307,35806) }, @{ Id='earthly-wax'; Month=5; Day=5; Name=U @(22320,33098,20043,36784) }, @{ Id='guan-di-descent'; Month=5; Day=13; Name=U @(20851,22307,24093,21531,38477,31070) }, @{ Id='cihang-enlightenment'; Month=6; Day=19; Name=U @(24904,33322,30495,20154,65288,35266,38899,65289,25104,36947,26085) }, @{ Id='guan-di-birthday'; Month=6; Day=24; Name=U @(20851,22307,24093,21531,22307,35806) }, @{ Id='zhongyuan'; Month=7; Day=15; Name=U @(20013,20803,22320,23448,22307,35806) }, @{ Id='queen-mother-birthday'; Month=7; Day=18; Name=U @(35199,29579,27597,22307,35806) }, @{ Id='doumu-birthday'; Month=9; Day=9; Name=U @(26007,23013,20803,21531,22307,35806) }, @{ Id='xiayuan'; Month=10; Day=15; Name=U @(19979,20803,27700,23448,22307,35806) }, @{ Id='kitchen-god'; Month=12; Day=23; Name=U @(31085,28790,29579) }
)
$repoRoot = Split-Path -Parent $PSScriptRoot
Write-Calendar 'SRC-BUDDHIST-HAN' (U @(27721,20256,20315,25945,26680,24515,26085)) (U @(27721,20256,20315,25945)) $hanBuddhist (Join-Path $repoRoot 'ical/v1/religion/han-buddhism/zh-CN.ics') 'Han Chinese Buddhist traditions; excludes Tibetan and Theravada Buddhism, fasting days, taboos, and local temple observances.'
Write-Calendar 'SRC-TAOIST' (U @(36947,25945,26680,24515,26085)) (U @(36947,25945)) $taoist (Join-Path $repoRoot 'ical/v1/religion/taoism/zh-CN.ics') 'Chinese Daoist traditions; excludes monthly fasting days, taboos, and local temple observances.'
