param(
    [string]$SolarTermsJson = 'tmp/solar-terms.json',
    [string]$Output = 'ical/v1/cn/traditional-public/zh-CN.ics',
    [int]$StartYear = 2025,
    [int]$EndYear = 2035
)
$ErrorActionPreference = 'Stop'

function U([int[]]$codes) { -join ($codes | ForEach-Object { [char]$_ }) }
function Escape-Ics([string]$value) {
    $value.Replace('\', '\\').Replace(';', '\;').Replace(',', '\,').Replace("`r", '').Replace("`n", '\n')
}
function Add-Event([string]$id, [datetime]$date, [string]$summary, [string]$category, [string]$description) {
    if ($date.Year -lt $StartYear -or $date.Year -gt $EndYear) { return }
    $events.Add([pscustomobject]@{
        Uid = "calrepo.cn.traditional-public.$id.$($date.ToString('yyyyMMdd'))@calrepo.com"
        Date = $date.ToString('yyyy-MM-dd')
        Summary = $summary
        Category = $category
        Description = $description
    })
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$solarPath = Join-Path $repoRoot $SolarTermsJson
$outputPath = Join-Path $repoRoot $Output
$solarJson = Get-Content -LiteralPath $solarPath -Raw | ConvertFrom-Json
$solarTerms = if ($solarJson -is [array]) { $solarJson } else { @($solarJson) }
$calendar = New-Object System.Globalization.ChineseLunisolarCalendar
$events = New-Object 'System.Collections.Generic.List[object]'
$traditionalCategory = U @(20013,22269,20256,32479,33410,26085)
$publicCategory = U @(20013,22269,20844,20849,20551,26085)
$statutorySuffix = U @(40,27861,41)
$traditionalDescription = 'Chinese traditional festival rule; lunar date generated by the .NET ChineseLunisolarCalendar.'
$statutoryDescription = 'Statutory base date. The annual State Council General Office notice controls the actual leave span and adjusted workdays.'
$partialDescription = 'Partial public holiday for the specified audience under the national holiday rules.'
$observanceDescription = 'China national observance recorded on its fixed Gregorian date.'

$lunarRules = @(
    @{ Id='new-years-eve'; Month=12; Day=0; Name=U @(38500,22805); English="Chinese New Year's Eve"; Nature='statutory' },
    @{ Id='spring-festival'; Month=1; Day=1; Name=U @(26149,33410); English='Chinese New Year'; Nature='statutory' },
    @{ Id='lantern'; Month=1; Day=15; Name=U @(20803,23477,33410); English='Lantern Festival'; Nature='traditional' },
    @{ Id='dragon-head'; Month=2; Day=2; Name=U @(40857,25260,22836); English='Dragon Head-Raising Day'; Nature='traditional' },
    @{ Id='shangsi'; Month=3; Day=3; Name=U @(19978,24051,33410); English='Shangsi Festival'; Nature='traditional' },
    @{ Id='dragon-boat'; Month=5; Day=5; Name=U @(31471,21320,33410); English='Dragon Boat Festival'; Nature='statutory' },
    @{ Id='qixi'; Month=7; Day=7; Name=U @(19971,22805); English='Qixi Festival'; Nature='traditional' },
    @{ Id='zhongyuan'; Month=7; Day=15; Name=U @(20013,20803,33410); English='Zhongyuan Festival'; Nature='traditional' },
    @{ Id='mid-autumn'; Month=8; Day=15; Name=U @(20013,31179,33410); English='Mid-Autumn Festival'; Nature='statutory' },
    @{ Id='double-ninth'; Month=9; Day=9; Name=U @(37325,38451,33410); English='Double Ninth Festival'; Nature='traditional' },
    @{ Id='laba'; Month=12; Day=8; Name=U @(33098,20843,33410); English='Laba Festival'; Nature='traditional' }
)

foreach ($lunarYear in ($StartYear - 1)..$EndYear) {
    foreach ($rule in $lunarRules) {
        $day = if ($rule.Day -eq 0) { $calendar.GetDaysInMonth($lunarYear, $rule.Month, 1) } else { $rule.Day }
        $date = $calendar.ToDateTime($lunarYear, $rule.Month, $day, 0, 0, 0, 0)
        $suffix = if ($rule.Nature -eq 'statutory') { $statutorySuffix } else { '' }
        $category = if ($rule.Nature -eq 'statutory') { $publicCategory } else { $traditionalCategory }
        $description = if ($rule.Nature -eq 'statutory') { $statutoryDescription } else { $traditionalDescription }
        Add-Event $rule.Id $date "$($rule.Name)$suffix | $($rule.English)" $category $description
    }
}

$termByYear = @{}
foreach ($term in $solarTerms) { $termByYear["$($term.year)-$($term.name_zh)"] = [datetime]$term.date }
foreach ($year in $StartYear..$EndYear) {
    $fixed = @(
        @{ Id='new-year'; Month=1; Day=1; Name=(U @(20803,26086)) + $statutorySuffix; English="New Year's Day"; Nature='statutory' },
        @{ Id='labour-day'; Month=5; Day=1; Name=(U @(21171,21160,33410)) + $statutorySuffix; English='Labour Day (statutory)'; Nature='statutory' },
        @{ Id='women-day'; Month=3; Day=8; Name=U @(22919,22899,33410); English="International Women's Day (partial public holiday)"; Nature='partial' },
        @{ Id='youth-day'; Month=5; Day=4; Name=U @(20116,22235,38738,24180,33410); English='Youth Day (partial public holiday)'; Nature='partial' },
        @{ Id='children-day'; Month=6; Day=1; Name=U @(20799,31461,33410); English="Children's Day (partial public holiday)"; Nature='partial' },
        @{ Id='army-day'; Month=8; Day=1; Name=U @(24314,20891,33410); English='Army Day (partial public holiday)'; Nature='partial' },
        @{ Id='arbor-day'; Month=3; Day=12; Name=U @(26893,26641,33410); English='Arbor Day'; Nature='observance' },
        @{ Id='party-anniversary'; Month=7; Day=1; Name=U @(20013,22269,20849,20135,20826,25104,31435,32426,24565,26085); English='Anniversary of the Founding of the Communist Party of China'; Nature='observance' },
        @{ Id='victory-day'; Month=9; Day=3; Name=U @(20013,22269,20154,27665,25239,26085,25112,20105,32988,21033,32426,24565,26085); English="Victory Day of the Chinese People's War of Resistance Against Japanese Aggression"; Nature='observance' },
        @{ Id='teachers-day'; Month=9; Day=10; Name=U @(25945,24072,33410); English="Teachers' Day"; Nature='observance' },
        @{ Id='martyrs-day'; Month=9; Day=30; Name=U @(28872,22763,32426,24565,26085); English='Martyrs Day'; Nature='observance' },
        @{ Id='constitution-day'; Month=12; Day=4; Name=U @(22269,23478,23466,27861,26085); English='National Constitution Day'; Nature='observance' }
    )
    foreach ($rule in $fixed) {
        $date = [datetime]::new($year, $rule.Month, $rule.Day)
        $description = if ($rule.Nature -eq 'statutory') { $statutoryDescription } elseif ($rule.Nature -eq 'partial') { $partialDescription } else { $observanceDescription }
        Add-Event $rule.Id $date $rule.Name $publicCategory $description
    }
    $qingming = $termByYear["$year-$(U @(28165,26126))"]
    if ($qingming) { Add-Event 'qingming' $qingming "$(U @(28165,26126,33410))$statutorySuffix | Qingming Festival (statutory)" $publicCategory $statutoryDescription }
    Add-Event 'national-day' ([datetime]::new($year, 10, 1)) "$(U @(22269,24198,33410))$statutorySuffix | National Day (statutory)" $publicCategory $statutoryDescription
}

$calendarName = U @(20013,22269,20256,32479,33410,26085,21450,20844,20849,20551,26085)
$lines = @(
    'BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CalRepo//China Traditional and Public Holidays//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',
    "X-WR-CALNAME:$calendarName",'X-WR-TIMEZONE:Asia/Shanghai','X-CALREPO-SOURCE-ID:SRC-CN-TRADITIONAL-PUBLIC','X-CALREPO-VERSION:2026.07.25'
)
foreach ($event in ($events | Sort-Object Date, Summary)) {
    $endDate = ([datetime]::ParseExact($event.Date, 'yyyy-MM-dd', $null)).AddDays(1).ToString('yyyyMMdd')
    $lines += @('BEGIN:VEVENT',"UID:$($event.Uid)",'DTSTAMP:20260725T080000Z',"DTSTART;VALUE=DATE:$($event.Date.Replace('-', ''))","DTEND;VALUE=DATE:$endDate", "SUMMARY:$(Escape-Ics $event.Summary)", "DESCRIPTION:$(Escape-Ics $event.Description)", "CATEGORIES:$(Escape-Ics $event.Category)",'END:VEVENT')
}
$lines += 'END:VCALENDAR'
$outputDirectory = Split-Path -Parent $outputPath
[IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[IO.File]::WriteAllBytes($outputPath, [Text.UTF8Encoding]::new($false).GetBytes(($lines -join "`r`n") + "`r`n"))
Write-Output "generated $($events.Count) events: $outputPath"
